### ISSUE TITLE
Attach request_id for each request

### ISSUE THREAD

**Issue by WindSoilder** [eopb/tide-tracing#16]
I think it would be useful if we can generate and log request_id for each request, like how [tracing-actix-web](https://github.com/LukeMathWalker/tracing-actix-web#unique-identifiers) does, then we can aggregate and tracing one request to get more information.

What do you think about this?

**Comment by eopb** [comment]
Hey, I'm sorry for taking so long to reply to this.

I would be happy to add such a feature if it's still wanted. @PortableNavi has a fork, I'd be happy to upstream a version of that if they would like to open a PR.

**Comment by PortableNavi** [comment]
Yes, I can open a PR.
